### ISSUE TITLE
Please update for stylelint v15

### ISSUE THREAD

**Issue by MartinX3** [nuxt-community/stylelint-module#69]

**Comment by daniluk4000** [comment]
@ricardogobbosouza

**Comment by MartinX3** [comment]
I removed this project.
It seems it is dead and won't get any updates.
If I'm informed correctly users should migrate to Nuxt 3 and its Vite Plugins instead.

**Comment by miroslavgeorgiev** [comment]
@ricardogobbosouza - the previous time it was again weeks or months until the module was update to the last stylelint version.
If you don't have time or wish to deal with this project - you better give rights to someone else to do that.

**Comment by ricardogobbosouza** [comment]
Sorry for delay

**Comment by ricardogobbosouza** [comment]
Added support stylelint v15 on v4.2.0

**Comment by MartinX3** [comment]
Thank you @ricardogobbosouza 

After updating to 4.2.0 I get the following warning in pnpm:
```
└─┬ @nuxtjs/stylelint-module 4.2.0
  └─┬ stylelint-webpack-plugin 2.4.0
    └── ✕ unmet peer stylelint@"^13.0.0 || ^14.0.0": found 15.2.0
```

and I still get the same error
```
 ERROR  StylelintError                                                                                                                                            friendly-errors 19:20:29

[stylelint] stylelint.createLinter is not a function 
```

So I need to remove this module again.

**Comment by ricardogobbosouza** [comment]
Thanks @MartinX3

**Comment by ricardogobbosouza** [comment]
Fixed https://github.com/nuxt-community/eslint-module/pull/80

**Comment by davidsandoz** [comment]
@ricardogobbosouza Is there any plan to fix [the error mentioned by Martin](https://github.com/nuxt-community/stylelint-module/issues/69#issuecomment-1460646755)? It would be great to have a fix in a v4.2.1 (in addition to v5.0.1), so that it's available for Nuxt.js 2 apps.

**Comment by ricardogobbosouza** [comment]
Release [v4.2.1(https://github.com/nuxt-community/stylelint-module/tree/v4.2.1)
